### ISSUE TITLE
Stop closing the socket on all :invalid payloads

### ISSUE THREAD

**Issue by queer** [queer/singyeong#143]
Man idk what I was thinking when I implemented this.

Some stuff (payload can't route, invalid metadata update, ...) should send an `:invalid` but NOT close, whereas some other stuff (malformed payload, ...) should close with either `:invalid` or `:goodbye`.

**Comment by FiniteReality** [comment]
IMHO:
- `:goodbye` should only be sent when Singyeong wants a client to disconnect, e.g. as part of load-balancing
- `:invalid` should be sent when an application-level error (i.e. unable to route, invalid metadata, etc.) occurs
- A new type, `:error`, should be sent when a protocol-level error occurs, and then the client should ideally disconnect after this, but Singyeong should time-out the connection if it does not disconnect on its own.
