### ISSUE TITLE
Support initial queues in identify payload 

### ISSUE THREAD

**Issue by PanKlipcio** [queer/singyeong#166]
Automatically performs QUEUE_REQUEST for the specified queues.

## Example payload:
```json
{
  "client_id": "19274eyuholdis3vhynurtlofkbhndvhvqkl34wjgyhnewri",
  "application_id": "my-cool-application",
  "queues": [
    "my-queue-name"
  ]
}
```

**Comment by queer** [comment]
I'm fine with adding this, but what's the specific use-case you're thinking of here?

**Comment by PanKlipcio** [comment]
Mostly, in my scripts, queues names are predefined and require a subscription only on connect. The queues themselves have an infinite number of use cases.

**Comment by queer** [comment]
:thinking: 

> and require a subscription only on connect.

Queues should remove the pending client when a message is dispatched to said client, thus requiring a resubscription. If it doesn't have this behaviour then it's a bug that needs to be fixed.

**Comment by PanKlipcio** [comment]
I misread the documentation, sorry.
